### ISSUE TITLE
YouTube Video Resize Fix not detected.

### ISSUE THREAD

**Issue by Butanediol** [cyfung1031/YouTube-Live-Borderless#1]
I installed [YouTube Video Resize Fix](https://greasyfork.org/scripts/457319) and enabled **YouTube WPR**. But it keeps showing "YouTube WPR is not yet installed" while watching regular YouTube videos and live streams. 

Screenshots:
<img width="2158" alt="image" src="https://github.com/cyfung1031/YouTube-Live-Borderless/assets/22426749/31d17ff3-79e1-4014-8df3-b3e7a73d9168">

Environment:
MacOS 13.4, Arc Browser(Chromium 114) with Stylus Beta
Enabled scripts and styles as below

<img width="239" alt="image" src="https://github.com/cyfung1031/YouTube-Live-Borderless/assets/22426749/983df2e8-5bed-4593-848f-0372f0076c63">

<img width="316" alt="image" src="https://github.com/cyfung1031/YouTube-Live-Borderless/assets/22426749/d482deae-41d6-41ea-877e-17f36d72b7fe">

---

Also, it seems that **YouTube WPR** is not compatible with **Always 2 Columns Mode**? If I enable WPR, it's not
 borderless anymore.

**Comment by cyfung1031** [comment]
Thanks for bug reporting. It is now fixed. Please update [YouTube Video Resize Fix](https://greasyfork.org/scripts/457319) to the latest version (>=0.3.3).

**Comment by cyfung1031** [comment]
> Also, it seems that YouTube WPR is not compatible with Always 2 Columns Mode? If I enable WPR, it's not
borderless anymore.

I think it was because YouTube WPR was not added by [YouTube Video Resize Fix](https://greasyfork.org/scripts/457319) due to the bug? Please let me know whether the issue is still there after your update.

**Comment by Butanediol** [comment]
It's working flawlessly right now! Really appreciate your work, thanks!
