### ISSUE TITLE
tab view youtubeと併用時に、特定の動画においてプログレスバーの表示が崩れる

### ISSUE THREAD

**Issue by ni1chigo2115** [cyfung1031/YouTube-Live-Borderless#2]
https://youtu.be/b3Wlv_nrSqI
ブラウザの機能でズームしている状態だとtab view youtubeと併用するとプログレスバーのレイアウトが崩れてしまうようです。
（チャプター分けされていると特に発生しやすいように感じます）
これはライブ動画では発生せず、通常の動画の時のみ発生するようです
![tvy_zoom_bugs](https://github.com/cyfung1031/YouTube-Live-Borderless/assets/23652237/1937d292-5253-4e2e-8661-46cd1c66150c)

ちなみにズーム率は115％です

**Comment by cyfung1031** [comment]
https://greasyfork.org/en/scripts/457319-youtube-video-resize-fix
