### ISSUE TITLE
YouTube Live Borderless breaks the mini player feature of Enhancer for Youtube browser extension

### ISSUE THREAD

**Issue by AomariDev** [cyfung1031/YouTube-Live-Borderless#4]
It didn't used to be a problem but some time ago it broke. It's not a big problem but just wanted to mention it if it's possible to fix it.

![MiniPlayerSettings](https://github.com/cyfung1031/YouTube-Live-Borderless/assets/5493998/ded217cc-c4d9-4e33-99ba-4c3ad6e5d927)

This is the mini player feature in the Enhancer for Youtube browser extension.

![MiniPlayerWIthFixPlayerHeightOverflowOff](https://github.com/cyfung1031/YouTube-Live-Borderless/assets/5493998/61cfcf15-2383-4955-abbb-994c621aff97)

This is how it should look like working normally.

![MiniPlayerWithFixPLayerHeightOverflowOn](https://github.com/cyfung1031/YouTube-Live-Borderless/assets/5493998/0b906812-e60e-4a8d-9818-605988f47142)

This is how it looks with "Fix Player Height Overflow" which is turned on by default. Turning it off fixes the problem but I'm not sure why it is on by default since it doesn't seem to visibly change anything for me.

**Comment by cyfung1031** [comment]
Fixed. By the way, [Tabview Youtube](https://greasyfork.org/en/scripts/428651-tabview-youtube) is recommended for using YouTube Live Borderless
